### ISSUE TITLE
About ERE dataset.

### ISSUE THREAD

**Issue by littlefive5** [PlusLabNLP/DEGREE#1]
I didn't find the three data LDC2015E29, LDC2015E68, LDC2015E78 on the LDC website? Is there a download url?

**Comment by huanghuidmml** [comment]
Have you found these data sets? Can you send me a copy? Thank you very much. My email is m13021933043@163.com

**Comment by littlefive5** [comment]
> Have you found these data sets? Can you send me a copy? Thank you very much. My email is [m13021933043@163.com](mailto:m13021933043@163.com)

Sorry, I didn't get the these data either.

**Comment by VioletPeng** [comment]
Hi all, sorry these datasets are not free, you need to get access to LDC catalog to access them. We're not in the position to share them privately, but many schools have the license. You can probably contact your librarian or your advisor to get access.

**Comment by huanghuidmml** [comment]
老



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 08/20/2022 06:30 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [PlusLabNLP/DEGREE] About ERE dataset. (Issue #1) |

Hi all, sorry these datasets are not free, you need to get access to LDC catalog to access them. We're not in the position to share them privately, but many schools have the license. You can probably contact your librarian or your advisor to get access.
