### ISSUE TITLE
Availability of Datasets?

### ISSUE THREAD

**Issue by demongolem-biz2** [PlusLabNLP/DEGREE#12]
I very much would like to try this approach, but I see the datasets supported are ace05e, ace05ep and ere.  Are any of the datasets freely available or are they all LDC items which have to be purchased?

If in fact they do have to be purchased, then is there a pointer to the format so that I can use my own data and coerce my data into the expected format?

**Comment by ej0cl6** [comment]
Unfortunately, you have to pay for them. You can build your own data in the OneIE format (https://github.com/dwadden/dygiepp#ace05-event) and use our preprocessing script for ace05e `processed_data/ace05e_dygieppformat`.
