### ISSUE TITLE
about argument evaluation

### ISSUE THREAD

**Issue by hlee-top** [PlusLabNLP/DEGREE#3]
Hello author, I have some ambiguity with the following code, I think it is to find the span of the trigger word, so cor_tri_span=self.predstr2span(pred[0])[0] should be changed to cor_tri_span=self.predstr2span(cor_tri[0])[0] 
Looking forward to your reply!

https://github.com/PlusLabNLP/DEGREE/blob/7fb6e4b15c1c81c70d15837e33eeb25b73b5679f/degree/template_generate_ace.py#L200-L209

**Comment by VioletPeng** [comment]
@ihungalexhsu @ej0cl6

**Comment by ihungalexhsu** [comment]
Hi,

Oh yes, you are correct. Thanks for catching this! However, FYI, I guess this might only affect the training results a little bit for e2e cases, and our final evaluation is not done using this function. I will modify the code correspondingly.
