### ISSUE TITLE
Question about the pre-processing

### ISSUE THREAD

**Issue by yhcc** [PlusLabNLP/DEGREE#4]
Hi, thanks to the interesting work and open-sourced code. When I read your pre-processing code, I am a little confused by some codes. Would you please help me out.

(1) Will any sentence being pruned because of the max_length in the following code?
https://github.com/PlusLabNLP/DEGREE/blob/7fb6e4b15c1c81c70d15837e33eeb25b73b5679f/degree/generate_data_degree_e2e.py#L69 
(2) Why to remove the nested entity?
https://github.com/PlusLabNLP/DEGREE/blob/7fb6e4b15c1c81c70d15837e33eeb25b73b5679f/degree/data.py#L109
(3) Why to remove multi role?
https://github.com/PlusLabNLP/DEGREE/blob/7fb6e4b15c1c81c70d15837e33eeb25b73b5679f/degree/data.py#L49

**Comment by yhcc** [comment]
It seems like that the (2) and (3) are frome the OneIE paper.

**Comment by ihungalexhsu** [comment]
Hi,

(1) In theory, yes. But as I remember, in the dataset we run (at least for ace), we won't get any instances being filtered. But I might need to double check

We do (2) & (3) because we want to fairly compare with the OneIE paper.
