### ISSUE TITLE
".pkl"files

### ISSUE THREAD

**Issue by simon-p-j-r** [PlusLabNLP/DEGREE#7]
hello, dear author. Where can I get  train_all.pkl, dev_all.pkl and test_all.pkl files?

**Comment by ej0cl6** [comment]
Hi, did you follow our commands in README to run `generate_data_degree_eae.py`/`generate_data_degree_e2e.py`/`generate_data_degree_ed.py`/ to generate the .pkl files first?

**Comment by simon-p-j-r** [comment]
Thanks!!! It's my carelessness.


but when I train degree(end2end), an error occured:


[2023-03-10 12:44:46] - data - Loaded 292257 instances from ./data/degree_e2e_ace05ep/train_all.pkl
[2023-03-10 12:44:47] - data - Loaded 13929 instances from ./data/degree_e2e_ace05ep/dev_all.pkl
[2023-03-10 12:44:47] - data - Loaded 10535 instances from ./data/degree_e2e_ace05ep/test_all.pkl
[2023-03-10 12:44:47] - model - Loading pre-trained model ./bart-large
[2023-03-10 12:45:40] - __main__ - Start training ...
[2023-03-10 12:45:40] - __main__ - ./output/degree_e2e_ace05ep/20230310_124441/train.log
[2023-03-10 12:45:40] - __main__ - Epoch 1
Train 1: &nbsp; 0%|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; | 0/9134 [00:00<?, ?it/s]Traceback (most recent call last):
&nbsp; File "degree/train_degree_e2e.py", line 106, in <module&gt;
&nbsp; &nbsp; loss = model(batch)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/pjr/DEGREE-master/DEGREE-master/degree/model.py", line 20, in forward
&nbsp; &nbsp; outputs = self.model(input_ids=batch.enc_idxs, 
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/transformers/modeling_bart.py", line 1066, in forward
&nbsp; &nbsp; outputs = self.model(
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/transformers/modeling_bart.py", line 914, in forward
&nbsp; &nbsp; encoder_outputs = self.encoder(
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/transformers/modeling_bart.py", line 352, in forward
&nbsp; &nbsp; x, attn = encoder_layer(x, attention_mask, output_attentions=output_attentions)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/transformers/modeling_bart.py", line 253, in forward
&nbsp; &nbsp; x, attn_weights = self.self_attn(
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/transformers/modeling_bart.py", line 672, in forward
&nbsp; &nbsp; q = self.q_proj(query) * self.scaling
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
&nbsp; &nbsp; return F.linear(input, self.weight, self.bias)
&nbsp; File "/home/net/anaconda3/envs/pjrDEGREE/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
&nbsp; &nbsp; return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
Train 1: &nbsp; 0%|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; | 0/9134 [00:01<?, ?it/s]



Did you have the error when you run the code? My virtual environment is exactly the same as Readme.
Thanks for your reply!!!!



I fix it, by install torch==1.7.1.
Thanks for your patient so much, I will close the issue.
Thanks again



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PlusLabNLP/DEGREE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 中午12:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PlusLabNLP/DEGREE] ".pkl"files (Issue #7)





 
Hi, did you follow our commands in README to run generate_data_degree_eae.py/generate_data_degree_e2e.py/generate_data_degree_ed.py/ to generate the .pkl files first?
